- hosts: localhost 
  gather_facts: False
  vars_prompt:
    - name: "vaultpass"
      prompt: "Provide vaultpass"

  tasks:
    - name: Vaultpass.
      debug:
        msg: "{{ vaultpass }}"

    - name: Create a vaultpass file
      copy:
        content: "{{ vaultpass }}"
        dest: "~/.config/lapsible_vaultpass"
        mode: 0400

