---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      dnf: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/crontab.yml
    - include: tasks/trash.yml
    - include: tasks/sudoers.yml
    - include: tasks/repositories.yml
    - include: tasks/packages.yml
    - include: tasks/flatpak.yml
    - include: tasks/kde.yml

