---
- hosts: localhost
  become: true
  vars:
      home: "{{out.stdout}}"
  pre_tasks:
    - name: update repositories
      dnf: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/crontab.yml
    - include: tasks/sudoers.yml
    - include: tasks/packages.yml
    - include: tasks/flatpak.yml

