---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - name: Install packages    
    dnf:
        name: ['htop', 'mc', 'vim', 'golang']
        state: present
