- name: nVidia driver enable
  command: dnf config-manager rpmfusion-nonfree-nvidia-driver --set-enabled
  become: true

- name: Install bumblebee nVidia packages
  dnf:
    name: ['akmod-nvidia','acpi','acpid']
    state: present

- name: Create group bumblebee
  group:
    name: bumblebee
    state: present

- name: Adding szydell to bumblebee group
  user:
    name: szydell
    groups: bumblebee
    append: yes


