- name: install cron job (szydell, clear trash)
  cron: user="szydell" name="clear trash" hour="*/1" job="/usr/bin/find $HOME/{Downloads,Documents,Pictures,Video}/trash/* -mtime +6 -type f -delete"

- name: install cron job (szydell, clear Downloads)
  cron: user="szydell" name="clear Downloads" hour="*/1" job="/usr/bin/find $HOME/Downloads* -mtime +30 -type f -delete"

- name: keep known_hosts up to date
  cron:
   user: "szydell"
   name: "known_hosts updater"
   job: "ansible-vault --vault-password-file ~/.config/lapsible_vaultpass encrypt ~/.ssh/known_hosts --output ~/development/lapsible/files/known_hosts && cd ~/development/lapsible && git add files/known_hosts && git commit -m 'known_hosts updater' files/known_hosts && git push"
   special_time: "daily"



#- file:
#    path: "~/logs"
#    state: directory
#  become: true
#  become_method: sudo
#  become_user: "ansible"

#- name: install cron job (ansible-pull)
  #  cron: user="ansible" name="ansible provision" minute="*/10" job="/usr/bin/ansible-pull --accept-host-key --private-key=$HOME/.ssh/id_rsa -o -U git@gitlab.com:szydell/laptak.git > $HOME/logs/ansible-$(date -I'minutes').log"

#- name: install cron job (clean logs)
#  cron: user="ansible" name="clear ansible logs" hour="*/1" job="/usr/bin/find $HOME/logs/ansible* -mtime +6 -type f -delete"

#- name: install cron job (clean empty logs)
#  cron: user="ansible" name="clear empty logs" hour="*/1" job="/usr/bin/find $HOME/logs/ansible* -type f -size -700c -mmin +179 -delete"
