- name: Add the flathub flatpak repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  become: true
  become_user: szydell

    #- name: Install the spotify flatpak
    #flatpak:
    #name:  https://s3.amazonaws.com/alexlarsson/spotify-repo/spotify.flatpakref
    #state: present



- name: Install Spotify
  command: flatpak install --assumeyes flathub com.spotify.Client
  become: true
  become_user: szydell

- name: Flatpak update
  command: flatpak update
  become: true
  become_user: szydell
