- vars_prompt:
    - name: "vaultpass"
      prompt: "Provide a vault pass"

- name: Create a vaultpass file
   copy: 
    content: "{{ vaultpass }}" 
    dest: "~/.config/lapsible_vaultpass"
    mode: 0400

