- name: Set Meta+l as default lock shortcut
  ini_file:
          path: ~/.config/kglobalshortcutsrc
          section: ksmserver
          option: Lock Session
          value: Meta+L\tScreensaver,Ctrl+Alt+L\tScreensaver,Lock Session
          backup: yes
          mode: 0600

- name: restart kglobalaccel
  become: szydell
  command: /usr/bin/kquitapp5 kglobalaccel5 && sleep 2s && kglobalaccel5 &

