#Import klucza do Negativo17 repository
- name: import key to verify Negativo17 repo
  rpm_key:
    state: present
    key: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh

- name: Add Negativo17 repository 
  yum_repository:
    name: n17_nVidia 
    description: Negativo17 nvidia repository
    baseurl: https://negativo17.org/repos/nvidia/fedora-$releasever/$basearch/
    gpgcheck: yes
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh


- name: Install nVidia packages
  dnf:
    name: ['nvidia-settings','kernel-devel','dkms-nvidia']
    state: present


- name: copy SDDM config
  copy: src=files/Xsetup dest="/etc/sddm/Xsetup" owner=root group=root mode=0755

- name: copy xorg config
  copy: src=files/xorg.conf dest="/etc/X11/xorg.conf" owner=root group=root mode=0644

