- name: Install dlang (dmd) snap
  command: snap install --classic dmd

- name: Install dlang (dub) snap
  command: snap install --classic dub

- git:
    repo: https://github.com/abraunegg/onedrive/
    dest: /home/szydell/development/onedrive
  become: true
  become_method: sudo
  become_user: "szydell"

- make:
    chdir: /home/szydell/development/onedrive
    params:
      DC: /var/lib/snapd/snap/bin/dmd
      NUM_THREADS: 4

- make:
    chdir: /home/szydell/development/onedrive
    target: install
  become: true

- name: create directory for onedrive configuration
  file: path="~/.config/onedrive/" state=directory mode=0700
  become: true
  become_user: "szydell"

- name: copy onedrive config
  copy: src=files/onedrive_config dest="~/.config/onedrive/config" owner=szydell group=szydell mode=0600
  become: true
  become_user: "szydell"

- name: copy onedrive token
  copy: src=files/onedrive_token dest="~/.config/onedrive/refresh_token" owner=szydell group=szydell mode=0600 decrypt=true
  become: true
  become_user: "szydell"

- name: enable and start onedrive
  systemd: 
    state: started
    enabled: yes
    name: onedrive@szydell.service


