- name: Install dlang (dmd) snap
  command: snap install --classic dmd

- name: Install dlang (dub) snap
  command: snap install --classic dub

- git:
    repo: https://github.com/abraunegg/onedrive/
    dest: /home/szydell/development/onedrive
  become: true
  become_method: sudo
  become_user: "szydell"

- make:
    chdir: /home/szydell/development/onedrive
    params:
      DC: /var/lib/snapd/snap/bin/dmd
      NUM_THREADS: 4

- make:
    chdir: /home/szydell/development/onedrive
    target: install
  become: true

