- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install packages
  dnf:
    name: ['@Development tools', 'snapd', 'htop', 'mc', 'vim', 'golang', 'flatpak', 'gcompris', 'gcompris-qt-activities', 'code', 'strace', 'vlc-extras', 'libcurl-devel', 'sqlite-devel']
    state: present

- name: Start snapd service, if not started
  service:
    name: snapd
    state: started

