- name: create directory for ssh keys
  file: path="~/.ssh" state=directory mode=0700
  become: true
  become_user: "szydell"

- name: copy public key
  copy: src=files/id_rsa.pub dest="~/.ssh/id_rsa.pub" owner=szydell group=szydell mode=0644
  become: true
  become_user: "szydell"

- name: copy private key
  copy: src=files/id_rsa dest="~/.ssh/id_rsa" owner=szydell group=szydell mode=0600 decrypt=true
  become: true
  become_user: "szydell"

- name: copy known hosts
  copy: src=files/known_hosts dest="~/.ssh/known_hosts" owner=szydell group=szydell mode=0600 decrypt=true
  become: true
  become_user: "szydell"

